---
- name: Listen for events using the event source plugin
  hosts: all
  
  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ dt_url }}"
        dt_api_token: "{{ dt_token }}"
        delay: 60

  rules:
    - name: Problem payload Dynatrace for Easytrade DB Failure
      #condition: event.title is match("Failure rate increase")
      condition: event.status == "OPEN" and (event.title == "JavaScript error rate increase" or event.title == "Failure rate increase") and (event.impactedEntities[0].name == "BrokerService" or event.impactedEntities[0].name == "TradeManagement")
      action:
        run_job_template:
          name: easytrade-fix
          organization: Default
          job_args:
              extra_vars:
                dt_easytrade_url: '{{ et_url }}'
                dt_api_token: '{{ dt_token }}'
                dt_api_url: '{{ dt_url }}'



   - name: Problem payload Dynatrace for Credit Card Service
      #condition: event.title is match("Failure rate increase")
      condition: event.status == "OPEN" and (event.title == "JavaScript error rate increase" or event.title == "Failure rate increase") and (event.impactedEntities[0].name == "OrderController" or event.rootCauseEntity == "OrderController")
      action:
        run_job_template:
          name: remediate_creditcard
          organization: Default
          job_args:
              extra_vars:
                dt_easytrade_url: '{{ et_url }}'
                dt_api_token: '{{ dt_token }}'
                dt_api_url: '{{ dt_url }}'
